# Generated by Django 3.2.9 on 2021-12-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0002_remove_deck_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='creator',
        ),
    ]
